---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: registry-secret-manager
  labels:
    app.kubernetes.io/name: registry-secret-manager

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-secret-manager

subjects:
  - kind: ServiceAccount
    name: registry-secret-manager
    namespace: {{ $.Release.Namespace }}
