---

apiVersion: v1
kind: Secret

metadata:
  name: registry-secret-manager
  labels:
    app.kubernetes.io/name: registry-secret-manager

type: Opaque
data:
  {{- if $.Values.ecr.region }}
  AWS_DEFAULT_REGION: {{ $.Values.ecr.region | b64enc }}
  AWS_REGION: {{ $.Values.ecr.region | b64enc }}
  {{- end }}

  {{- if and $.Values.ecr.accessKeyId $.Values.ecr.secretAccessKey }}
  AWS_ACCESS_KEY_ID: {{ $.Values.ecr.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.ecr.secretAccessKey | b64enc }}
  {{- end }}

  {{- if $.Values.ecr.role }}
  AWS_ROLE_ARN: {{ $.Values.ecr.role | b64enc }}
  AWS_WEB_IDENTITY_TOKEN_FILE: {{ "/var/run/secrets/amazonaws.com/serviceaccount/token" | b64enc }}
  AWS_STS_REGIONAL_ENDPOINTS: {{ "regional" | b64enc }}
  {{- end }}

  {{- if and $.Values.dockerHub.username $.Values.dockerHub.password $.Values.dockerHub.endpoint }}
  DOCKER_HUB_USERNAME: {{ $.Values.dockerHub.username | b64enc }}
  DOCKER_HUB_PASSWORD: {{ $.Values.dockerHub.password | b64enc }}
  DOCKER_HUB_ENDPOINT: {{ $.Values.dockerHub.endpoint | b64enc }}
  {{- end }}
