---

apiVersion: v1
kind: Secret

metadata:
  name: registry-secret-manager
  labels:
    app.kubernetes.io/name: registry-secret-manager

type: Opaque
data:
  AWS_DEFAULT_REGION: {{ $.Values.ecr.region | b64enc }}
  AWS_ACCESS_KEY_ID: {{ $.Values.ecr.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ $.Values.ecr.secretAccessKey | b64enc }}

  DOCKER_HUB_USERNAME: {{ $.Values.dockerHub.username | b64enc }}
  DOCKER_HUB_PASSWORD: {{ $.Values.dockerHub.password | b64enc }}
  DOCKER_HUB_ENDPOINT: {{ $.Values.dockerHub.endpoint | b64enc }}
