---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: registry-secret-manager
  labels:
    app.kubernetes.io/name: registry-secret-manager

spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: registry-secret-manager
