---

apiVersion: v1
kind: Service

metadata:
  name: registry-secret-manager
  labels:
    app.kubernetes.io/name: registry-secret-manager

spec:
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
    - name: controller
      port: 443
      targetPort: controller
  selector:
    app.kubernetes.io/name: registry-secret-manager
