on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Verify
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    env:
      CI: 1
      GO111MODULE: on
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Go mod verify
        run: go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

      - name: Go tests
        run: go test -race -v ./... -coverprofile=coverage.out -covermode=atomic

      - uses: codecov/codecov-action@v2.0.3
        with:
          files: ./coverage.out
          fail_ci_if_error: true
