on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Verify
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
    env:
      CI: 1
      GO111MODULE: on
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make verify
